services:
  reverse_proxy_new:
    image: nginx:alpine
    container_name: reverse_proxy_new
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount ไฟล์ SSL certificates
    networks:
      - frontend
      - backend

  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./Container1:/usr/share/nginx/html
    networks:
      - backend

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./Container2:/usr/share/nginx/html
    networks:
      - backend

  web3:
    image: nginx:alpine
    container_name: web3
    volumes:
      - ./Container3:/usr/share/nginx/html
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge