
services:
  reverse_proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount ไฟล์ SSL certificates
    networks:
      - frontend
      - backend

  container1:
    build: ./Container1 
    container_name: container1
    volumes:
      - ./Container1/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  container2:
    image: nginx:alpine
    container_name: container2
    volumes:
      - ./Container2:/usr/share/nginx/html
      - ./Container2/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge