version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  web1:
    image: your-web1-image
    networks:
      - webnet

  web2:
    image: your-web2-image
    networks:
      - webnet

  web3:
    image: your-web3-image
    networks:
      - webnet

networks:
  webnet:
